# Site settings
title: Belgium's Most Wanted
email: cgc.digital@police.belgium.eu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: fedpol_pers
github_username:  fedpolbelgium

# Build settings
markdown: kramdown
permalink: pretty
