# Site settings
title: Belgium's Most Wanted
email: cgc.digital@police.belgium.eu
description: "first draft of the MW Belgium website"
baseurl: ""
url: "http://fedpolbelgium.github.io/m05tw1nt3d"
twitter_username: federalepolitie
github_username:  fedpolbelgium

# Build settings
markdown: kramdown
permalink: pretty
